databases:
  - name: care-management-db
    plan: free
    databaseName: care_management
    ipAllowList: []

services:
  - type: web
    name: care-management-tool
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn care_management.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: care-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ""
      - key: PYTHON_VERSION
        value: "3.11.6"
