# Generated by Django 4.2.16 on 2025-11-25 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("new", "新規"),
                            ("update", "更新"),
                            ("change", "区分変更"),
                            ("discharge", "退院"),
                            ("information", "情報提供"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="アセスメントの理由",
                    ),
                ),
                (
                    "assessment_type_other",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="アセスメントの理由その他",
                    ),
                ),
                (
                    "interview_location",
                    models.CharField(
                        choices=[
                            ("room", "居室"),
                            ("home", "自宅"),
                            ("hospital", "病院"),
                            ("facility", "施設"),
                            ("other", "その他"),
                        ],
                        max_length=30,
                        verbose_name="面談場所",
                    ),
                ),
                (
                    "interview_location_other",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="面談場所その他",
                    ),
                ),
                (
                    "basic_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="生活歴、本人・家族の希望等",
                        verbose_name="基本情報",
                    ),
                ),
                (
                    "insurance_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="介護度、負担割合、医療保険等",
                        verbose_name="保険情報",
                    ),
                ),
                (
                    "family_situation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="家族情報",
                        verbose_name="家族状況",
                    ),
                ),
                (
                    "living_situation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="住居環境、設備等",
                        verbose_name="居住状況",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="介護サービス、福祉用具等",
                        verbose_name="利用サービス",
                    ),
                ),
                (
                    "health_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="疾患、医師、服薬、アレルギー等",
                        verbose_name="健康状態",
                    ),
                ),
                (
                    "physical_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="皮膚疾患、感染症、身長体重等",
                        verbose_name="身体状況",
                    ),
                ),
                (
                    "cognitive_function",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="認知症、BPSD、会話等",
                        verbose_name="認知機能",
                    ),
                ),
                (
                    "basic_activities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="寝返り、起き上がり、移乗等",
                        verbose_name="基本動作",
                    ),
                ),
                (
                    "adl",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="食事、入浴、排泄等",
                        verbose_name="ADL",
                    ),
                ),
                (
                    "iadl",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="調理、掃除、洗濯等",
                        verbose_name="IADL",
                    ),
                ),
                (
                    "general_assessment",
                    models.TextField(blank=True, verbose_name="総合所見"),
                ),
                (
                    "support_goals",
                    models.TextField(blank=True, verbose_name="支援目標"),
                ),
                (
                    "total_score",
                    models.IntegerField(blank=True, null=True, verbose_name="総合得点"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "下書き"), ("completed", "完了")],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="clients.client",
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "アセスメント",
                "verbose_name_plural": "アセスメント",
                "ordering": ["-assessment_date", "-created_at"],
            },
        ),
    ]
