# Generated by Django 4.2.16 on 2026-05-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0043_add_medical_institution"),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="family_doctor_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family1_assessments",
                to="clients.medicalinstitution",
                verbose_name="かかりつけ医①",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="family_doctor_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family2_assessments",
                to="clients.medicalinstitution",
                verbose_name="かかりつけ医②",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="family_doctor_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family3_assessments",
                to="clients.medicalinstitution",
                verbose_name="かかりつけ医③",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="family_doctor_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family4_assessments",
                to="clients.medicalinstitution",
                verbose_name="かかりつけ医④",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="main_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_assessments",
                to="clients.medicalinstitution",
                verbose_name="主治医",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="visiting_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visiting_assessments",
                to="clients.medicalinstitution",
                verbose_name="往診医",
            ),
        ),
    ]
