# Generated by Django 4.2.16 on 2026-02-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="施設名")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("千種区", "千種区"),
                            ("東区", "東区"),
                            ("北区", "北区"),
                            ("西区", "西区"),
                            ("中村区", "中村区"),
                            ("中区", "中区"),
                            ("昭和区", "昭和区"),
                            ("瑞穂区", "瑞穂区"),
                            ("熱田区", "熱田区"),
                            ("中川区", "中川区"),
                            ("港区", "港区"),
                            ("南区", "南区"),
                            ("守山区", "守山区"),
                            ("緑区", "緑区"),
                            ("名東区", "名東区"),
                            ("天白区", "天白区"),
                            ("豊橋市", "豊橋市"),
                            ("岡崎市", "岡崎市"),
                            ("一宮市", "一宮市"),
                            ("瀬戸市", "瀬戸市"),
                            ("半田市", "半田市"),
                            ("春日井市", "春日井市"),
                            ("豊川市", "豊川市"),
                            ("津島市", "津島市"),
                            ("碧南市", "碧南市"),
                            ("刈谷市", "刈谷市"),
                            ("安城市", "安城市"),
                            ("西尾市", "西尾市"),
                            ("蒲郡市", "蒲郡市"),
                            ("犬山市", "犬山市"),
                            ("常滑市", "常滑市"),
                            ("江南市", "江南市"),
                            ("小牧市", "小牧市"),
                            ("稲沢市", "稲沢市"),
                            ("新城市", "新城市"),
                            ("東海市", "東海市"),
                            ("大府市", "大府市"),
                            ("知多市", "知多市"),
                            ("知立市", "知立市"),
                            ("尾張旭市", "尾張旭市"),
                            ("高浜市", "高浜市"),
                            ("岩倉市", "岩倉市"),
                            ("豊明市", "豊明市"),
                            ("日進市", "日進市"),
                            ("田原市", "田原市"),
                            ("愛西市", "愛西市"),
                            ("清須市", "清須市"),
                            ("北名古屋市", "北名古屋市"),
                            ("弥富市", "弥富市"),
                            ("みよし市", "みよし市"),
                            ("あま市", "あま市"),
                            ("長久手市", "長久手市"),
                            ("その他", "その他"),
                        ],
                        max_length=50,
                        verbose_name="地域",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="住所"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "unit_private",
                    models.BooleanField(default=False, verbose_name="ユニット型個室"),
                ),
                (
                    "unit_semi_private",
                    models.BooleanField(default=False, verbose_name="ユニット型準個室"),
                ),
                (
                    "traditional_private",
                    models.BooleanField(default=False, verbose_name="従来型個室"),
                ),
                (
                    "traditional_multi",
                    models.BooleanField(default=False, verbose_name="従来型多床室"),
                ),
                (
                    "capacity",
                    models.IntegerField(blank=True, null=True, verbose_name="定員数"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
            ],
            options={
                "verbose_name": "特養施設",
                "verbose_name_plural": "特養施設",
                "ordering": ["region", "name"],
            },
        ),
    ]
