# Generated by Django 4.2.16 on 2026-02-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_alter_facility_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="unit_semi_private",
        ),
        migrations.AddField(
            model_name="facility",
            name="unit_multi",
            field=models.BooleanField(default=False, verbose_name="ユニット型多床室"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="traditional_multi",
            field=models.BooleanField(default=False, verbose_name="多床室"),
        ),
    ]
