# Generated by Django 4.2.16 on 2026-02-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_remove_facility_unit_semi_private_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="fax",
            field=models.CharField(blank=True, max_length=20, verbose_name="FAX番号"),
        ),
        migrations.AddField(
            model_name="facility",
            name="homepage_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="ホームページURL"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="kaigo_kohyo_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                verbose_name="介護サービス情報公表システムURL",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="town",
            field=models.CharField(blank=True, max_length=100, verbose_name="町名"),
        ),
    ]
