# Generated by Django 4.2.16 on 2026-02-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0004_facility_fax_facility_homepage_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["region", "name"],
                "verbose_name": "施設",
                "verbose_name_plural": "施設",
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("特別養護老人ホーム", "特別養護老人ホーム"),
                    ("養護老人ホーム", "養護老人ホーム"),
                    ("軽費老人ホーム", "軽費老人ホーム"),
                    ("有料老人ホーム", "有料老人ホーム"),
                    ("サービス付き高齢者向け住宅", "サービス付き高齢者向け住宅"),
                    ("介護老人保健施設", "介護老人保健施設"),
                    ("介護医療院", "介護医療院"),
                    ("グループホーム", "グループホーム"),
                    ("その他", "その他"),
                ],
                default="特別養護老人ホーム",
                max_length=50,
                verbose_name="施設種別",
            ),
        ),
    ]
