# Generated by Django 4.2.16 on 2026-02-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0005_alter_facility_options_facility_facility_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="is_community_based",
            field=models.BooleanField(default=False, verbose_name="地域密着型"),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_wide_area",
            field=models.BooleanField(default=False, verbose_name="広域型"),
        ),
    ]
