# Generated by Django 4.2.16 on 2026-02-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0006_facility_is_community_based_facility_is_wide_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="is_nursing_care_type",
            field=models.BooleanField(default=False, verbose_name="介護付き"),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_residential_type",
            field=models.BooleanField(default=False, verbose_name="住宅型"),
        ),
    ]
