# Generated by Django 4.2.16 on 2026-02-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0007_facility_is_nursing_care_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="is_keihi_a",
            field=models.BooleanField(default=False, verbose_name="A型"),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_keihi_b",
            field=models.BooleanField(default=False, verbose_name="B型"),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_keihi_carehouse",
            field=models.BooleanField(default=False, verbose_name="ケアハウス"),
        ),
    ]
