# Generated by Django 4.2.16 on 2026-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0008_facility_is_keihi_a_facility_is_keihi_b_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="is_nursing_care_type",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="is_residential_type",
        ),
        migrations.AddField(
            model_name="facility",
            name="is_tokutei_shisetsu",
            field=models.BooleanField(
                default=False, verbose_name="特定施設入居者生活介護指定あり"
            ),
        ),
    ]
