# Generated by Django 4.2.16 on 2026-02-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0009_remove_facility_is_nursing_care_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="is_zaitaku_kyoka",
            field=models.BooleanField(default=False, verbose_name="在宅強化型"),
        ),
    ]
