# Generated by Django 4.2.16 on 2025-11-25 00:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="被保険者番号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                ("furigana", models.CharField(max_length=100, verbose_name="ふりがな")),
                ("birth_date", models.DateField(verbose_name="生年月日")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "男性"),
                            ("female", "女性"),
                            ("other", "その他"),
                        ],
                        max_length=10,
                        verbose_name="性別",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="電話番号"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                (
                    "care_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("independent", "自立"),
                            ("support1", "要支援1"),
                            ("support2", "要支援2"),
                            ("care1", "要介護1"),
                            ("care2", "要介護2"),
                            ("care3", "要介護3"),
                            ("care4", "要介護4"),
                            ("care5", "要介護5"),
                        ],
                        max_length=20,
                        verbose_name="要介護度",
                    ),
                ),
                (
                    "certification_date",
                    models.DateField(blank=True, null=True, verbose_name="認定日"),
                ),
                (
                    "certification_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="認定期間（開始）"
                    ),
                ),
                (
                    "certification_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="認定期間（終了）"
                    ),
                ),
                (
                    "care_burden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1割負担", "1割負担"),
                            ("2割負担", "2割負担"),
                            ("3割負担", "3割負担"),
                        ],
                        max_length=10,
                        verbose_name="負担割合",
                    ),
                ),
                (
                    "burden_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="負担割合期間（開始）"
                    ),
                ),
                (
                    "burden_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="負担割合期間（終了）"
                    ),
                ),
                (
                    "medical_insurance_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="医療保険種類"
                    ),
                ),
                (
                    "medical_insurer_name_issuer",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="保険者の名称及び交付者名",
                    ),
                ),
                (
                    "medical_insurer_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="医療保険保険者番号"
                    ),
                ),
                (
                    "medical_insurance_symbol",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="被保険者番号（記号）"
                    ),
                ),
                (
                    "medical_insurance_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="被保険者番号（番号）"
                    ),
                ),
                (
                    "family_name1",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="家族氏名（1人目）"
                    ),
                ),
                (
                    "family_relationship1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spouse", "配偶者"),
                            ("child", "子"),
                            ("parent", "親"),
                            ("sibling", "兄弟姉妹"),
                            ("grandchild", "孫"),
                            ("grandparent", "祖父母"),
                            ("other_relative", "その他親族"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="続柄（1人目）",
                    ),
                ),
                (
                    "family_address1",
                    models.TextField(blank=True, verbose_name="住所（1人目）"),
                ),
                (
                    "family_living_status1",
                    models.CharField(
                        blank=True,
                        choices=[("together", "同居"), ("separate", "別居")],
                        max_length=10,
                        verbose_name="同居有無（1人目）",
                    ),
                ),
                (
                    "family_care_status1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary_caregiver", "主たる介護者"),
                            ("support_caregiver", "介護協力者"),
                            ("no_care", "介護なし"),
                        ],
                        max_length=20,
                        verbose_name="介護状況（1人目）",
                    ),
                ),
                (
                    "family_employment1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "選択してください"),
                            ("employed", "就労中"),
                            ("unemployed", "無職"),
                            ("retired", "退職"),
                            ("homemaker", "専業主婦(夫)"),
                            ("student", "学生"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="就労状況（1人目）",
                    ),
                ),
                (
                    "family_contact1",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="連絡先（1人目）"
                    ),
                ),
                (
                    "family_notes1",
                    models.TextField(blank=True, verbose_name="備考（1人目）"),
                ),
                (
                    "family_name2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="家族氏名（2人目）"
                    ),
                ),
                (
                    "family_relationship2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spouse", "配偶者"),
                            ("child", "子"),
                            ("parent", "親"),
                            ("sibling", "兄弟姉妹"),
                            ("grandchild", "孫"),
                            ("grandparent", "祖父母"),
                            ("other_relative", "その他親族"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="続柄（2人目）",
                    ),
                ),
                (
                    "family_address2",
                    models.TextField(blank=True, verbose_name="住所（2人目）"),
                ),
                (
                    "family_living_status2",
                    models.CharField(
                        blank=True,
                        choices=[("together", "同居"), ("separate", "別居")],
                        max_length=10,
                        verbose_name="同居有無（2人目）",
                    ),
                ),
                (
                    "family_care_status2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary_caregiver", "主たる介護者"),
                            ("support_caregiver", "介護協力者"),
                            ("no_care", "介護なし"),
                        ],
                        max_length=20,
                        verbose_name="介護状況（2人目）",
                    ),
                ),
                (
                    "family_employment2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "選択してください"),
                            ("employed", "就労中"),
                            ("unemployed", "無職"),
                            ("retired", "退職"),
                            ("homemaker", "専業主婦(夫)"),
                            ("student", "学生"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="就労状況（2人目）",
                    ),
                ),
                (
                    "family_contact2",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="連絡先（2人目）"
                    ),
                ),
                (
                    "family_notes2",
                    models.TextField(blank=True, verbose_name="備考（2人目）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "利用者",
                "verbose_name_plural": "利用者",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "不具合報告"),
                            ("feature", "新機能提案"),
                            ("improvement", "改善要望"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("content", models.TextField(verbose_name="詳細内容")),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        default="medium",
                        max_length=20,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "未対応"),
                            ("in_progress", "対応中"),
                            ("completed", "完了"),
                            ("rejected", "却下"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="報告元ページURL"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="0000",
                        help_text="4桁の数字",
                        max_length=4,
                        verbose_name="閲覧パスワード",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
            ],
            options={
                "verbose_name": "フィードバック",
                "verbose_name_plural": "フィードバック",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegionalSupportCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="事業所名")),
                (
                    "office_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="事業所番号"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="所在地"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("tsu", "津市"),
                            ("suzuka", "鈴鹿市"),
                            ("kameyama", "亀山市"),
                            ("matsusaka", "松阪市"),
                            ("ise", "伊勢市"),
                            ("kuwana", "桑名市"),
                            ("yokkaichi", "四日市市"),
                            ("toba", "鳥羽市"),
                            ("owase", "尾鷲市"),
                            ("kumano", "熊野市"),
                            ("iga", "伊賀市"),
                            ("nabari", "名張市"),
                            ("inabe", "いなべ市"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="地域区分",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "地域包括支援センター",
                "verbose_name_plural": "地域包括支援センター",
                "ordering": ["area", "office_number"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="加算名")),
                (
                    "addon_type",
                    models.CharField(
                        choices=[
                            ("functional_training", "機能訓練加算"),
                            ("bathing", "入浴加算"),
                            ("dementia", "認知症対応型加算"),
                            ("nutrition", "栄養改善加算"),
                            ("oral_care", "口腔機能向上加算"),
                            ("transportation", "送迎減算"),
                            ("large_scale", "大規模減算"),
                            ("other", "その他"),
                        ],
                        max_length=30,
                        verbose_name="加算タイプ",
                    ),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="単位数"
                    ),
                ),
                (
                    "is_addition",
                    models.BooleanField(
                        default=True,
                        help_text="True=加算、False=減算",
                        verbose_name="加算/減算",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "加算種別",
                "verbose_name_plural": "加算種別",
            },
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="事業所名")),
                (
                    "service_category",
                    models.CharField(
                        choices=[
                            ("day_service", "デイサービス"),
                            ("home_helper", "ヘルパー"),
                            ("visiting_nurse", "訪問看護"),
                            ("welfare_equipment", "福祉用具"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="サービスカテゴリ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "事業所",
                "verbose_name_plural": "事業所",
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="サービス名")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("day_service", "デイサービス"),
                            ("home_helper", "ヘルパー"),
                            ("visiting_nurse", "訪問看護"),
                            ("welfare_equipment", "福祉用具"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "unit_per_minute",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="1分あたりの単位数"
                    ),
                ),
                (
                    "total_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="時間が含まれている場合の総単位数",
                        max_digits=8,
                        null=True,
                        verbose_name="合計単位数",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="サービス名に時間が含まれている場合",
                        null=True,
                        verbose_name="実施時間（分）",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "サービス種別",
                "verbose_name_plural": "サービス種別",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, verbose_name="姓"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="名"),
                ),
                (
                    "last_name_kana",
                    models.CharField(blank=True, max_length=50, verbose_name="セイ"),
                ),
                (
                    "first_name_kana",
                    models.CharField(blank=True, max_length=50, verbose_name="メイ"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="電話番号"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理者"),
                            ("care_manager", "ケアマネージャー"),
                            ("staff", "一般スタッフ"),
                        ],
                        default="staff",
                        max_length=20,
                        verbose_name="役職",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        choices=[("annotsuroman", "安濃津ろまん")],
                        default="annotsuroman",
                        max_length=50,
                        verbose_name="事業所",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kyotaku", "居宅"),
                            ("helper", "ヘルパー"),
                            ("helper_general_affairs", "ヘルパー庶務"),
                            ("day_service", "デイサービス"),
                            ("day_service_general_affairs", "デイサービス庶務"),
                            ("visiting_nurse", "訪問看護"),
                            ("visiting_nurse_general_affairs", "訪問看護庶務"),
                            ("office", "事務所"),
                        ],
                        max_length=100,
                        verbose_name="所属部署",
                    ),
                ),
                (
                    "color_theme",
                    models.CharField(
                        choices=[("current", "パステルカラー（明るく優しい色合い）")],
                        default="current",
                        max_length=20,
                        verbose_name="カラーテーマ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="無効にするとログインできなくなります",
                        verbose_name="有効",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザープロファイル",
                "verbose_name_plural": "ユーザープロファイル",
            },
        ),
        migrations.CreateModel(
            name="LimitCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年")),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="月",
                    ),
                ),
                (
                    "care_manager_units",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ケアマネ設定単位",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "限度額試算",
                "verbose_name_plural": "限度額試算",
                "ordering": ["-year", "-month"],
                "unique_together": {("client", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="FeedbackReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="返信内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="clients.feedback",
                        verbose_name="フィードバック",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="返信者",
                    ),
                ),
            ],
            options={
                "verbose_name": "フィードバック返信",
                "verbose_name_plural": "フィードバック返信",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCreationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "kyotaku_service_plan_request",
                                "居宅サービス計画作成依頼書",
                            ),
                            (
                                "kyotaku_preventive_service_plan_request",
                                "介護予防サービス計画作成依頼書",
                            ),
                            ("care_plan", "ケアプラン"),
                            ("assessment", "アセスメント"),
                            ("other", "その他"),
                        ],
                        max_length=50,
                        verbose_name="書類種別",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(max_length=200, verbose_name="書類名"),
                ),
                (
                    "form_data",
                    models.JSONField(
                        help_text="フォームの入力データ", verbose_name="入力内容"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "下書き"), ("completed", "完成")],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_histories",
                        to="clients.client",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "書類作成履歴",
                "verbose_name_plural": "書類作成履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientDementiaStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requires_dementia_care",
                    models.BooleanField(default=False, verbose_name="認知症対応が必要"),
                ),
                (
                    "dementia_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "レベル1"),
                            ("2", "レベル2"),
                            ("3", "レベル3"),
                            ("4", "レベル4"),
                        ],
                        max_length=10,
                        verbose_name="認知症レベル",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dementia_status",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "利用者別認知症状況",
                "verbose_name_plural": "利用者別認知症状況",
            },
        ),
        migrations.CreateModel(
            name="AdditionalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="手動入力時のみ使用",
                        null=True,
                        verbose_name="実施時間（分）",
                    ),
                ),
                ("date_provided", models.DateField(verbose_name="実施日")),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        help_text="手動入力用（後方互換性）",
                        max_length=100,
                        verbose_name="事業所名",
                    ),
                ),
                (
                    "has_functional_training",
                    models.BooleanField(default=False, verbose_name="機能訓練加算"),
                ),
                (
                    "has_bathing",
                    models.BooleanField(default=False, verbose_name="入浴加算"),
                ),
                (
                    "has_cognitive_function",
                    models.BooleanField(default=False, verbose_name="認知機能加算"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "limit_calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_services",
                        to="clients.limitcalculation",
                        verbose_name="限度額試算",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.serviceprovider",
                        verbose_name="事業所",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.servicetype",
                        verbose_name="サービス種別",
                    ),
                ),
            ],
            options={
                "verbose_name": "追加サービス",
                "verbose_name_plural": "追加サービス",
                "ordering": ["-date_provided", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderAddOnSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.serviceaddon",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addon_settings",
                        to="clients.serviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "事業所別加算設定",
                "verbose_name_plural": "事業所別加算設定",
                "unique_together": {("provider", "addon")},
            },
        ),
    ]
