# Generated by Django 4.2.16 on 2025-11-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="insurance_number",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="被保険者番号"
            ),
        ),
    ]
