# Generated by Django 4.2.16 on 2025-11-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_homecaresupportoffice_userprofile_home_care_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalsupportcenter",
            name="area",
            field=models.CharField(
                choices=[
                    ("tsu", "津市"),
                    ("suzuka", "鈴鹿市"),
                    ("kameyama", "亀山市"),
                    ("matsusaka", "松阪市"),
                    ("ise", "伊勢市"),
                    ("yokkaichi", "四日市市"),
                    ("kuwana", "桑名市"),
                    ("iga", "伊賀市"),
                    ("nabari", "名張市"),
                    ("inabe", "いなべ市"),
                    ("kumano", "熊野市"),
                    ("owase", "尾鷲市"),
                    ("toba", "鳥羽市"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=20,
                verbose_name="地域区分",
            ),
        ),
    ]
