# Generated by Django 4.2.16 on 2026-02-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_regionalsupportcenter_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="dementia_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "選択してください"),
                    ("independent", "自立"),
                    ("I", "I"),
                    ("IIa", "IIa"),
                    ("IIb", "IIb"),
                    ("IIIa", "IIIa"),
                    ("IIIb", "IIIb"),
                    ("IV", "IV"),
                    ("M", "M"),
                ],
                max_length=20,
                verbose_name="認知症日常生活自立度",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="difficult_disease",
            field=models.BooleanField(default=False, verbose_name="難病申請"),
        ),
        migrations.AddField(
            model_name="client",
            name="disability_handbook",
            field=models.BooleanField(default=False, verbose_name="身体障がい者手帳"),
        ),
        migrations.AddField(
            model_name="client",
            name="disability_handbook_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="障害種別"),
        ),
        migrations.AddField(
            model_name="client",
            name="disability_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "選択してください"),
                    ("independent", "自立"),
                    ("J1", "J1"),
                    ("J2", "J2"),
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=20,
                verbose_name="障がい者日常生活自立度",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="life_protection",
            field=models.BooleanField(default=False, verbose_name="生活保護"),
        ),
    ]
