# Generated by Django 4.2.16 on 2026-02-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_add_disability_dementia_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="disability_welfare",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="障害福祉サービス受給者証"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="disability_welfare_cert_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="障害福祉 認定有効期間（終了）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="disability_welfare_cert_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="障害福祉 認定有効期間（開始）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="disability_welfare_decision_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="障害福祉 支給決定期間（終了）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="disability_welfare_decision_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="障害福祉 支給決定期間（開始）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="high_cost_care",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="高額介護サービス費"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="high_cost_combined",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="高額医療・高額介護合算療養費"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="limit_cert",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="負担限度額認定証"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="limit_cert_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="負担限度額 有効期間（終了）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="limit_cert_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="負担限度額 有効期間（開始）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="nhi_limit_cert",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="国保限度額適用・減額認定証"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="nhi_limit_cert_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="国保限度額 有効期間（終了）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="nhi_limit_cert_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="国保限度額 有効期間（開始）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="specific_medical",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="特定医療費（指定難病）受給者証"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="specific_medical_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="特定医療費 有効期間（終了）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="specific_medical_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="特定医療費 有効期間（開始）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="welfare_medical",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="福祉医療費受給者証"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="welfare_medical_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="福祉医療費 有効期間（終了）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="welfare_medical_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="福祉医療費 有効期間（開始）"
            ),
        ),
    ]
