# Generated by Django 4.2.16 on 2026-03-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_client_disability_welfare_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="medical_insurance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "選択してください"),
                    ("national_health", "国民健康保険"),
                    ("latter_stage_elderly", "後期高齢者医療"),
                    ("health_insurance_association", "健康保険（協会けんぽ）"),
                    ("health_insurance_union", "健康保険（組合）"),
                    ("mutual_aid", "共済組合"),
                    ("seamen", "船員保険"),
                    ("other", "その他"),
                ],
                max_length=100,
                verbose_name="医療保険種類",
            ),
        ),
    ]
