# Generated by Django 4.2.16 on 2026-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_alter_client_medical_insurance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="medical_insurance_branch",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="被保険者番号（枝番）"
            ),
        ),
    ]
