# Generated by Django 4.2.16 on 2026-03-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_client_medical_insurance_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="difficult_disease_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="難病疾患名"
            ),
        ),
    ]
