# Generated by Django 4.2.16 on 2026-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_client_difficult_disease_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("care_manager", "介護支援専門員"),
                    ("social_worker", "社会福祉士"),
                    ("nurse", "看護師"),
                    ("care_worker", "介護福祉士"),
                    ("other", "その他"),
                ],
                max_length=50,
                verbose_name="業種",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.CharField(
                choices=[("annotsuroman", "居宅介護支援事業所 安濃津ろまん")],
                default="annotsuroman",
                max_length=50,
                verbose_name="事業所",
            ),
        ),
    ]
