# Generated by Django 4.2.16 on 2026-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_userprofile_job_type_alter_userprofile_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="郵便番号"),
        ),
    ]
