# Generated by Django 4.2.16 on 2026-03-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_client_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="disability_handbook_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1級"),
                    ("2", "2級"),
                    ("3", "3級"),
                    ("4", "4級"),
                    ("5", "5級"),
                    ("6", "6級"),
                ],
                max_length=10,
                verbose_name="障害等級",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="disability_handbook_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("visual", "視覚障害"),
                    ("hearing_balance", "聴覚・平衡機能障害"),
                    ("voice_language", "音声・言語・そしゃく機能障害"),
                    ("limb_upper", "肢体不自由（上肢）"),
                    ("limb_lower", "肢体不自由（下肢）"),
                    ("limb_trunk", "肢体不自由（体幹）"),
                    ("heart", "心臓機能障害"),
                    ("kidney", "じん臓機能障害"),
                    ("respiratory", "呼吸器機能障害"),
                    ("bladder_rectum", "ぼうこう又は直腸機能障害"),
                    ("small_intestine", "小腸機能障害"),
                    ("immune", "免疫機能障害"),
                    ("liver", "肝臓機能障害"),
                ],
                max_length=100,
                verbose_name="障害種別",
            ),
        ),
    ]
