# Generated by Django 4.2.16 on 2026-03-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_alter_client_dementia_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="difficult_disease_other",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="難病疾患名（その他）"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="difficult_disease_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("parkinson", "パーキンソン病"),
                    ("ulcerative_colitis", "潰瘍性大腸炎"),
                    ("crohn", "クローン病"),
                    ("sle", "全身性エリテマトーデス"),
                    ("als", "筋萎縮性側索硬化症 (ALS)"),
                    ("spinocerebellar_degeneration", "脊髄小脳変性症"),
                    ("ms", "多発性硬化症"),
                    ("myasthenia_gravis", "重症筋無力症"),
                    ("aplastic_anemia", "再生不良性貧血"),
                    ("idiopathic_femoral_head_necrosis", "特発性大腿骨頭壊死症"),
                    ("progressive_supranuclear_palsy", "進行性核上性麻痺"),
                    ("cbd", "大脳皮質基底核変性症"),
                    ("other", "その他"),
                ],
                max_length=200,
                verbose_name="難病疾患名",
            ),
        ),
    ]
