# Generated by Django 4.2.16 on 2026-03-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0014_client_difficult_disease_other_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="medical_burden",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1割負担", "1割負担"),
                    ("2割負担", "2割負担"),
                    ("3割負担", "3割負担"),
                ],
                max_length=10,
                verbose_name="医療保険負担割合",
            ),
        ),
    ]
