# Generated by Django 4.2.16 on 2026-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_client_medical_burden"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="medical_insurance_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="医療保険 有効期間（終了）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="medical_insurance_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="医療保険 有効期間（開始）"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="family_employment1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("employed", "就労中"),
                    ("unemployed", "無職"),
                    ("retired", "退職"),
                    ("homemaker", "専業主婦(夫)"),
                    ("student", "学生"),
                    ("other", "その他"),
                ],
                max_length=20,
                verbose_name="就労状況（1人目）",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="family_employment2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("employed", "就労中"),
                    ("unemployed", "無職"),
                    ("retired", "退職"),
                    ("homemaker", "専業主婦(夫)"),
                    ("student", "学生"),
                    ("other", "その他"),
                ],
                max_length=20,
                verbose_name="就労状況（2人目）",
            ),
        ),
    ]
