# Generated by Django 4.2.16 on 2026-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0016_add_medical_insurance_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="daily_living_assessed_cert_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="自立度判定時の認定期間終了日"
            ),
        ),
    ]
