# Generated by Django 4.2.16 on 2026-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_add_daily_living_assessed_cert_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="prev_dementia_level",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="前回の認知症日常生活自立度"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="prev_disability_level",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="前回の障がい者日常生活自立度"
            ),
        ),
    ]
