# Generated by Django 4.2.16 on 2026-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0018_add_prev_daily_living_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="prev_dementia_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("independent", "自立"),
                    ("I", "I"),
                    ("IIa", "IIa"),
                    ("IIb", "IIb"),
                    ("IIIa", "IIIa"),
                    ("IIIb", "IIIb"),
                    ("IV", "IV"),
                    ("M", "M"),
                ],
                max_length=20,
                verbose_name="前回の認知症日常生活自立度",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="prev_disability_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----------"),
                    ("independent", "自立"),
                    ("J1", "J1"),
                    ("J2", "J2"),
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=20,
                verbose_name="前回の障がい者日常生活自立度",
            ),
        ),
    ]
