# Generated by Django 4.2.16 on 2026-04-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0019_add_choices_to_prev_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="family_relationship1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spouse", "配偶者"),
                    ("child", "子"),
                    ("eldest_son", "長男"),
                    ("second_son", "次男"),
                    ("third_son", "三男"),
                    ("eldest_daughter", "長女"),
                    ("second_daughter", "次女"),
                    ("third_daughter", "三女"),
                    ("parent", "親"),
                    ("sibling", "兄弟姉妹"),
                    ("grandchild", "孫"),
                    ("grandparent", "祖父母"),
                    ("other_relative", "その他親族"),
                    ("other", "その他"),
                ],
                max_length=20,
                verbose_name="続柄（1人目）",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="family_relationship2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spouse", "配偶者"),
                    ("child", "子"),
                    ("eldest_son", "長男"),
                    ("second_son", "次男"),
                    ("third_son", "三男"),
                    ("eldest_daughter", "長女"),
                    ("second_daughter", "次女"),
                    ("third_daughter", "三女"),
                    ("parent", "親"),
                    ("sibling", "兄弟姉妹"),
                    ("grandchild", "孫"),
                    ("grandparent", "祖父母"),
                    ("other_relative", "その他親族"),
                    ("other", "その他"),
                ],
                max_length=20,
                verbose_name="続柄（2人目）",
            ),
        ),
    ]
