# Generated by Django 4.2.16 on 2026-04-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0020_alter_client_family_relationship1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="family_relationship_detail1",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="続柄詳細（1人目）"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="family_relationship_detail2",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="続柄詳細（2人目）"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="family_relationship1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spouse", "配偶者"),
                    ("child", "子"),
                    ("child_in_law", "子の配偶者"),
                    ("parent", "父母"),
                    ("parent_in_law", "義父母"),
                    ("sibling", "兄弟姉妹"),
                    ("grandchild", "孫"),
                    ("other_relative", "その他親族"),
                    ("non_family", "家族以外"),
                ],
                max_length=20,
                verbose_name="続柄（1人目）",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="family_relationship2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spouse", "配偶者"),
                    ("child", "子"),
                    ("child_in_law", "子の配偶者"),
                    ("parent", "父母"),
                    ("parent_in_law", "義父母"),
                    ("sibling", "兄弟姉妹"),
                    ("grandchild", "孫"),
                    ("other_relative", "その他親族"),
                    ("non_family", "家族以外"),
                ],
                max_length=20,
                verbose_name="続柄（2人目）",
            ),
        ),
    ]
