# Generated by Django 4.2.16 on 2026-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0021_client_family_relationship_detail1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecaresupportoffice",
            name="furigana",
            field=models.CharField(blank=True, max_length=100, verbose_name="フリガナ"),
        ),
    ]
