# Generated by Django 4.2.16 on 2026-04-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0022_add_furigana_to_homecaresupportoffice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcreationhistory",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("kyotaku_service_plan_request", "居宅サービス計画作成依頼書"),
                    (
                        "kyotaku_preventive_service_plan_request",
                        "介護予防サービス計画作成依頼書",
                    ),
                    ("ltc_renewal", "更新認定申請書"),
                    ("ltc_change", "区分変更申請書"),
                    ("ltc_withdrawal", "認定申請取下書"),
                    (
                        "careplan_info_request",
                        "介護サービス計画作成に係る資料提供申請書",
                    ),
                    ("care_plan", "ケアプラン"),
                    ("assessment", "アセスメント"),
                    ("other", "その他"),
                ],
                max_length=50,
                verbose_name="書類種別",
            ),
        ),
    ]
