# Generated by Django 4.2.16 on 2026-04-20 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0023_ltc_withdrawal_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="charge_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="担当ケアマネージャー",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="charge_manager_other",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="担当ケアマネージャー（手入力）",
            ),
        ),
        migrations.AlterField(
            model_name="documentcreationhistory",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("kyotaku_service_plan_request", "居宅サービス計画作成依頼書"),
                    (
                        "kyotaku_preventive_service_plan_request",
                        "介護予防サービス計画作成依頼書",
                    ),
                    ("ltc_renewal", "更新認定申請書"),
                    ("ltc_change", "区分変更申請書"),
                    ("ltc_withdrawal", "認定申請取下書"),
                    ("ltc_doctor_change", "認定申請主治医変更届出書"),
                    (
                        "careplan_info_request",
                        "介護サービス計画作成に係る資料提供申請書",
                    ),
                    ("care_plan", "ケアプラン"),
                    ("assessment", "アセスメント"),
                    ("other", "その他"),
                ],
                max_length=50,
                verbose_name="書類種別",
            ),
        ),
    ]
