# Generated by Django 4.2.16 on 2026-04-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0026_add_kyotaku_selection_confirmation_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="KyotakuServiceOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("houmon", "訪問介護"),
                            ("tsusho", "通所介護"),
                            ("fukushi", "福祉用具貸与"),
                            ("chiiki", "地域密着型通所介護"),
                        ],
                        max_length=20,
                        verbose_name="サービス種別",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="順番")),
                (
                    "office_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="事業所番号"
                    ),
                ),
                (
                    "office_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="事業所名"
                    ),
                ),
                (
                    "corp_name",
                    models.CharField(blank=True, max_length=100, verbose_name="法人名"),
                ),
            ],
            options={
                "verbose_name": "居宅サービス確認書事業所",
                "verbose_name_plural": "居宅サービス確認書事業所",
                "ordering": ["service_type", "order"],
                "unique_together": {("service_type", "order")},
            },
        ),
    ]
