# Generated by Django 4.2.16 on 2026-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0027_add_kyotaku_service_office"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareServiceOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="事業所名")),
                (
                    "person_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="担当者名"
                    ),
                ),
                (
                    "office_type",
                    models.CharField(
                        choices=[("naibu", "内部"), ("gaibu", "外部")],
                        default="gaibu",
                        max_length=10,
                        verbose_name="区分",
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="FAX番号"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "介護サービス事業所",
                "verbose_name_plural": "介護サービス事業所",
                "ordering": ["office_type", "sort_order", "name"],
            },
        ),
    ]
