# Generated by Django 4.2.16 on 2026-04-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0028_add_care_service_office"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careserviceoffice",
            options={
                "ordering": ["office_type", "name"],
                "verbose_name": "介護サービス事業所",
                "verbose_name_plural": "介護サービス事業所",
            },
        ),
        migrations.RemoveField(
            model_name="careserviceoffice",
            name="person_name",
        ),
        migrations.RemoveField(
            model_name="careserviceoffice",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="careserviceoffice",
            name="furigana",
            field=models.CharField(blank=True, max_length=100, verbose_name="フリガナ"),
        ),
        migrations.AddField(
            model_name="careserviceoffice",
            name="persons",
            field=models.JSONField(blank=True, default=list, verbose_name="担当者名"),
        ),
        migrations.AddField(
            model_name="careserviceoffice",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
        ),
    ]
