# Generated by Django 4.2.16 on 2026-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0029_update_care_service_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="careserviceoffice",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="住所"),
        ),
        migrations.AddField(
            model_name="careserviceoffice",
            name="office_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="事業所番号"
            ),
        ),
        migrations.AddField(
            model_name="careserviceoffice",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="郵便番号"),
        ),
    ]
