# Generated by Django 4.2.16 on 2026-04-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0030_add_address_fields_to_care_service_office"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careserviceoffice",
            options={
                "ordering": ["name"],
                "verbose_name": "介護サービス事業所",
                "verbose_name_plural": "介護サービス事業所",
            },
        ),
        migrations.RemoveField(
            model_name="careserviceoffice",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="careserviceoffice",
            name="office_type",
        ),
    ]
