# Generated by Django 4.2.16 on 2026-04-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0031_simplify_care_service_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="careserviceoffice",
            name="service_types",
            field=models.JSONField(blank=True, default=list, verbose_name="事業所種類"),
        ),
    ]
