# Generated by Django 4.2.16 on 2026-04-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_add_service_types_to_care_service_office"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careserviceoffice",
            name="service_types",
        ),
        migrations.AddField(
            model_name="careserviceoffice",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "（未選択）"),
                    ("訪問介護", "訪問介護"),
                    ("訪問看護", "訪問看護"),
                    ("訪問入浴介護", "訪問入浴介護"),
                    ("訪問リハビリテーション", "訪問リハビリテーション"),
                    ("通所介護", "通所介護"),
                    ("通所リハビリテーション", "通所リハビリテーション"),
                    ("地域密着型通所介護", "地域密着型通所介護"),
                    ("短期入所生活介護", "短期入所生活介護"),
                    ("短期入所療養介護", "短期入所療養介護"),
                    ("福祉用具貸与", "福祉用具貸与"),
                    ("特定福祉用具販売", "特定福祉用具販売"),
                    ("小規模多機能型居宅介護", "小規模多機能型居宅介護"),
                ],
                max_length=50,
                verbose_name="事業所種類",
            ),
        ),
    ]
