# Generated by Django 4.2.16 on 2026-05-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0034_alter_careserviceoffice_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="careserviceoffice",
            name="office_type",
            field=models.CharField(
                choices=[("external", "外部"), ("internal", "内部")],
                default="external",
                max_length=10,
                verbose_name="事業所区分",
            ),
        ),
    ]
