# Generated by Django 4.2.16 on 2026-05-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0036_seed_internal_care_offices"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingPlaceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="場所名")),
                (
                    "is_other",
                    models.BooleanField(default=False, verbose_name="その他（手入力）"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
            ],
            options={
                "verbose_name": "開催予定場所",
                "verbose_name_plural": "開催予定場所",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
