# Generated by Django 4.2.16 on 2026-05-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0038_seed_meeting_place_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingAgendaOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="検討内容")),
                (
                    "is_other",
                    models.BooleanField(default=False, verbose_name="その他（手入力）"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
            ],
            options={
                "verbose_name": "今回の検討内容",
                "verbose_name_plural": "今回の検討内容",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
