# Generated by Django 4.2.16 on 2026-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0040_seed_meeting_agenda_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaxMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="いつもお世話になっております。\n{office_name}の{user_name}です。\n\nサービス担当者会議開催のご案内をお送りします。ご多忙のところ誠に恐れ入りますが、\nご確認いただけますようよろしくお願いいたします。",
                        verbose_name="本文テンプレート",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "FAX本文テンプレート",
                "verbose_name_plural": "FAX本文テンプレート",
            },
        ),
    ]
