# Generated by Django 4.2.16 on 2026-05-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0042_seed_fax_message_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(max_length=200, verbose_name="医療機関名"),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="医師氏名"
                    ),
                ),
                (
                    "doctor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("主治医", "主治医"),
                            ("往診医", "往診医"),
                            ("かかりつけ医", "かかりつけ医"),
                            ("専門医", "専門医"),
                            ("その他", "その他"),
                        ],
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="FAX番号"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="住所"),
                ),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "医療機関",
                "verbose_name_plural": "医療機関",
                "ordering": ["hospital_name", "doctor_name"],
            },
        ),
    ]
