# Generated by Django 4.2.16 on 2026-05-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0043_add_medical_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalinstitution",
            name="hospital_furigana",
            field=models.CharField(blank=True, max_length=200, verbose_name="フリガナ"),
        ),
    ]
