# Generated by Django 4.2.16 on 2026-05-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0044_add_hospital_furigana"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalinstitution",
            options={
                "ordering": ["hospital_name"],
                "verbose_name": "医療機関",
                "verbose_name_plural": "医療機関",
            },
        ),
        migrations.RemoveField(
            model_name="medicalinstitution",
            name="doctor_name",
        ),
        migrations.AddField(
            model_name="medicalinstitution",
            name="doctors",
            field=models.JSONField(
                blank=True, default=list, verbose_name="医師氏名リスト"
            ),
        ),
    ]
