# Generated by Django 4.2.16 on 2026-05-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0045_replace_doctor_name_with_doctors"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecaresupportoffice",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="会社名"),
        ),
    ]
