# Generated by Django 4.2.16 on 2026-05-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0046_add_company_name_to_home_care_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecaresupportoffice",
            name="staff_names",
            field=models.JSONField(
                blank=True, default=list, verbose_name="担当者リスト"
            ),
        ),
    ]
