# Generated by Django 4.2.16 on 2026-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0047_add_staff_names_to_home_care_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalinstitution",
            name="corp_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="法人名"),
        ),
    ]
