# Generated by Django 4.2.16 on 2026-06-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0049_add_company_name_to_care_service_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionalsupportcenter",
            name="fax",
            field=models.CharField(blank=True, max_length=20, verbose_name="FAX番号"),
        ),
        migrations.AddField(
            model_name="regionalsupportcenter",
            name="persons",
            field=models.JSONField(blank=True, default=list, verbose_name="担当者名"),
        ),
    ]
