# Generated by Django 4.2.16 on 2026-06-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0050_add_fax_persons_to_support_center"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="項目名")),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("per_day", "円/日"),
                            ("per_month", "円/月"),
                            ("per_meal", "円/食"),
                            ("multi", "複数単価"),
                        ],
                        default="per_day",
                        max_length=20,
                        verbose_name="単価種別",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="単価")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="並び順"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="表示")),
                (
                    "item_key",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="内部キー"
                    ),
                ),
                (
                    "extra_prices",
                    models.JSONField(blank=True, default=list, verbose_name="追加単価"),
                ),
            ],
            options={
                "verbose_name": "有償サービス",
                "verbose_name_plural": "有償サービス",
                "ordering": ["order", "id"],
            },
        ),
    ]
